#!/bin/bash

extract_paths() {
    echo "$1" | awk '/paths:/ {p=1; next} p && /^-/ {sub(/- /,""); print}'
}

extract_launchers() {
    echo "$1" | awk '/launchers:/ {p=1; next} p && /^-/ {sub(/- /,""); print}'
}

load_config() {
    if stat "${HOME}/.config/code-launcher/config.yaml" &> /dev/null; then
        echo "Loading config..."
        yaml_content=$(cat ~/.config/code-launcher/config.yaml)
        extract_paths "$yaml_content"
        extract_launchers "$yaml_content"
    else
        echo "Error: Config not found!"
        echo "Help: https://github.com/jtomaspm/code-launcher/tree/main?tab=readme-ov-file#configuration"
        exit 1
    fi
}

main() {
    load_config
}

main